/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was org.freedesktop.systemd1.Timer.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "systemd_timer_interface.h"

/*
 * Implementation of interface class OrgFreedesktopSystemd1TimerInterface
 */

using namespace Qt::StringLiterals;
OrgFreedesktopSystemd1TimerInterface::OrgFreedesktopSystemd1TimerInterface(const QString &service,
                                                                           const QString &path,
                                                                           const QDBusConnection &_connection,
                                                                           QObject *parent)
    : OrgFreedesktopSystemd1UnitInterface(service, path, _connection, staticInterfaceName(), parent)
{
}

OrgFreedesktopSystemd1TimerInterface::~OrgFreedesktopSystemd1TimerInterface()
{
}

#include "moc_systemd_timer_interface.cpp"
