// This file was generated by a modified version of qdbusxml2cpp
// SPDX-FileCopyrightText: 2025 Carl Schwan <carl@carlschwan.eu>
// SPDX-License-Identifier: LGPL-2.0-or-later

#include "systemd_timer_interface.h"

/*
 * Implementation of interface class OrgFreedesktopSystemd1TimerInterface
 */

using namespace Qt::StringLiterals;
OrgFreedesktopSystemd1TimerInterface::OrgFreedesktopSystemd1TimerInterface(const QString &service,
                                                                           const QString &path,
                                                                           const QDBusConnection &_connection,
                                                                           QObject *parent)
    : OrgFreedesktopSystemd1UnitInterface(service, path, _connection, staticInterfaceName(), parent)
{
}

OrgFreedesktopSystemd1TimerInterface::~OrgFreedesktopSystemd1TimerInterface()
{
}

#include "moc_systemd_timer_interface.cpp"
